import 'package:swapnojatri/core/localization/app_strings.dart';
import 'package:swapnojatri/data/models/project_model.dart';
import 'package:swapnojatri/data/models/investment_model.dart';
import 'package:swapnojatri/data/models/transaction_model.dart';
import 'package:swapnojatri/data/models/expense_model.dart';
import 'package:swapnojatri/data/models/asset_model.dart';
import 'package:swapnojatri/data/models/profit_period_model.dart';
import 'package:swapnojatri/data/models/distribution_model.dart';
import 'package:swapnojatri/data/models/document_model.dart';
import 'package:swapnojatri/data/models/notification_model.dart';
import 'package:swapnojatri/data/models/kyc_model.dart';
import 'package:swapnojatri/data/models/audit_log_model.dart';
import 'package:swapnojatri/data/models/user_model.dart';

/// Seed data representing real-world Swapnojatri operations and LandVest 100
class ProjectSeeds {
  ProjectSeeds._();

  static final ProjectModel landVest100 = ProjectModel(
    id: 'proj-lv-100',
    code: 'LV100',
    name: 'LandVest 100',
    nameBn: 'ল্যান্ডভেস্ট ১০০',
    category: 'Commercial & Residential Land',
    location: 'Hemayetpur, Savar, Dhaka',
    description: AppStrings.landVestDescEn,
    descriptionBn: AppStrings.landVestDescBn,
    targetFund: 2550000.0,
    totalShares: 100,
    pricePerShare: 25500.0,
    minShares: 1,
    maxShares: 4,
    allocatedShares: 74,
    status: ProjectStatus.active,
    startDate: DateTime(2026, 1, 15),
    targetEndDate: DateTime(2027, 6, 30),
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&auto=format&fit=crop&q=80',
    highlights: [
      'Prime Dhaka-Aricha highway proximity',
      'Clear CS, SA, RS, BS records with legal vetting',
      'Mutation & DCR clearance verified',
      'Expected 22-28% capital appreciation window',
    ],
    milestones: [
      Milestone(
        id: 'm1',
        title: 'Project Inception & Legal Due Diligence',
        titleBn: 'প্রকল্প শুরু ও আইনি যাচাইকরণ',
        description: 'Comprehensive title search, mouza map matching, and vetting by Supreme Court advocate.',
        date: DateTime(2026, 1, 15),
        isCompleted: true,
        documentRef: 'DOC-LEGAL-01',
      ),
      Milestone(
        id: 'm2',
        title: 'Funding Round Launch (100 Shares)',
        titleBn: 'তহবিল সংগ্রহ শুরু (১০০ শেয়ার)',
        description: 'Official launch of LandVest 100 share subscription at ৳25,500/share.',
        date: DateTime(2026, 2, 1),
        isCompleted: true,
      ),
      Milestone(
        id: 'm3',
        title: 'Sub-Registry Deed Execution (Baina & Registry)',
        titleBn: 'সাব-রেজিস্ট্রি দলিল সম্পাদন',
        description: 'Execution of formal deed at Savar Sub-Registry Office with government stamp duty.',
        date: DateTime(2026, 4, 10),
        isCompleted: true,
        documentRef: 'DOC-DEED-4982',
      ),
      Milestone(
        id: 'm4',
        title: 'Land Demarcation & Perimeter Fencing',
        titleBn: 'জমির সীমানা নির্ধারণ ও সীমানা প্রাচীর',
        description: 'Physical pillar survey and security boundary fencing across 22.5 decimals.',
        date: DateTime(2026, 6, 20),
        isCompleted: true,
      ),
      Milestone(
        id: 'm5',
        title: 'Final Mutation & Khatian Issuance',
        titleBn: 'নামজারি ও খতিয়ান চূড়ান্তকরণ',
        description: 'AC Land Savar mutation approval and Dakhila payment completion.',
        date: DateTime(2026, 8, 15),
        isCompleted: true,
        documentRef: 'DOC-MUT-2026',
      ),
      Milestone(
        id: 'm6',
        title: 'Strategic Asset Monetization / Payout Phase',
        titleBn: 'পরিকল্পিত সম্পদ নগদায়ন ও লভ্যাংশ বণ্টন',
        description: 'Planned commercial lease exit / block distribution to investors.',
        date: DateTime(2027, 6, 30),
        isCompleted: false,
      ),
    ],
  );

  static final UserModel defaultInvestor = UserModel(
    id: 'usr-investor-01',
    name: 'Ohiur Rahman Ohi',
    phone: '+880 1712-345678',
    email: 'ohi.investor@swapnojatri.com',
    role: UserRole.investor,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    isKycVerified: true,
    memberSince: DateTime(2026, 2, 10),
  );

  static final UserModel defaultAdmin = UserModel(
    id: 'usr-admin-01',
    name: 'Tanvir Ahmed',
    phone: '+880 1819-998877',
    email: 'tanvir.admin@swapnojatri.com',
    role: UserRole.admin,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    isKycVerified: true,
    memberSince: DateTime(2025, 11, 1),
  );

  static final List<InvestmentModel> defaultInvestments = [
    InvestmentModel(
      id: 'inv-101',
      investmentNo: 'SJ-LV100-0042',
      userId: 'usr-investor-01',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      shares: 4,
      unitPrice: 25500.0,
      grossAmount: 102000.0,
      fees: 0.0,
      netAmount: 102000.0,
      status: InvestmentStatus.allocated,
      allocatedLotNumbers: ['LOT-041', 'LOT-042', 'LOT-043', 'LOT-044'],
      paymentMethod: 'Bank Transfer (City Bank)',
      paymentReference: 'TXN-CBL-8920194',
      createdAt: DateTime(2026, 2, 12, 14, 30),
      verifiedAt: DateTime(2026, 2, 13, 10, 15),
    ),
  ];

  static final List<TransactionModel> defaultTransactions = [
    TransactionModel(
      id: 'txn-501',
      investmentId: 'inv-101',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      userId: 'usr-investor-01',
      type: TransactionType.investment,
      direction: TransactionDirection.debit,
      amount: 102000.0,
      balanceAfter: 102000.0,
      reference: 'TXN-CBL-8920194',
      paymentMethod: 'City Bank Ltd (EFTN)',
      status: TransactionStatus.completed,
      createdAt: DateTime(2026, 2, 12, 14, 30),
      description: 'Subscription for 4 Shares in LandVest 100 (Lots 041-044)',
    ),
    TransactionModel(
      id: 'txn-502',
      investmentId: 'inv-101',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      userId: 'usr-investor-01',
      type: TransactionType.profitDistribution,
      direction: TransactionDirection.credit,
      amount: 10000.0,
      balanceAfter: 112000.0,
      reference: 'DIST-2026-H1-042',
      paymentMethod: 'bKash Merchant Payout',
      status: TransactionStatus.completed,
      createdAt: DateTime(2026, 7, 5, 11, 20),
      description: 'H1 2026 Land Lease Dividend Payout (4 Shares @ ৳2,500)',
    ),
  ];

  static final List<ExpenseModel> defaultExpenses = [
    ExpenseModel(
      id: 'exp-01',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      category: 'Land Acquisition',
      description: 'Primary deed execution and seller token payment (Plot #418)',
      payee: 'Haji Mohammad Ali (Land Owner)',
      amount: 1550000.0,
      expenseDate: DateTime(2026, 4, 10),
      status: ExpenseStatus.approved,
      approvedBy: 'Tanvir Ahmed (Finance Manager)',
      documentRef: 'VOUCHER-EXP-001.pdf',
      voucherNo: 'VCH-LV100-01',
    ),
    ExpenseModel(
      id: 'exp-02',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      category: 'Government Registry & Taxes',
      description: 'Sub-Registry stamp duty, local govt tax & registration fees',
      payee: 'District Sub-Registry Office, Savar',
      amount: 285000.0,
      expenseDate: DateTime(2026, 4, 12),
      status: ExpenseStatus.approved,
      approvedBy: 'Tanvir Ahmed (Finance Manager)',
      documentRef: 'TAX-CHALLAN-891.pdf',
      voucherNo: 'VCH-LV100-02',
    ),
    ExpenseModel(
      id: 'exp-03',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      category: 'Legal Due Diligence',
      description: 'Supreme Court Advocate title vetting, search report & legal fee',
      payee: 'Hossain & Associates Legal Firm',
      amount: 65000.0,
      expenseDate: DateTime(2026, 2, 5),
      status: ExpenseStatus.approved,
      approvedBy: 'Tanvir Ahmed (Finance Manager)',
      documentRef: 'LEGAL-INVOICE-04.pdf',
      voucherNo: 'VCH-LV100-03',
    ),
    ExpenseModel(
      id: 'exp-04',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      category: 'Site Demarcation & Fencing',
      description: 'RCC concrete boundary pillars, barbed wire & survey charges',
      payee: 'Dhaka Civil Engineering Works',
      amount: 125000.0,
      expenseDate: DateTime(2026, 6, 22),
      status: ExpenseStatus.approved,
      approvedBy: 'Tanvir Ahmed (Finance Manager)',
      documentRef: 'FENCE-BILL-33.pdf',
      voucherNo: 'VCH-LV100-04',
    ),
    ExpenseModel(
      id: 'exp-05',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      category: 'Mutation & DCR',
      description: 'Assistant Commissioner (Land) mutation government fees & khazna',
      payee: 'AC Land Office, Savar Circle',
      amount: 25000.0,
      expenseDate: DateTime(2026, 8, 16),
      status: ExpenseStatus.approved,
      approvedBy: 'Tanvir Ahmed (Finance Manager)',
      documentRef: 'DAKHILA-2026-99.pdf',
      voucherNo: 'VCH-LV100-05',
    ),
  ];

  static final List<AssetModel> defaultAssets = [
    AssetModel(
      id: 'ast-lv-01',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      assetType: 'Freehold Land (স্বত্ব দখলীয় জমি)',
      title: 'Plot 418, Mouza Hemayetpur',
      titleBn: 'প্লট ৪১৮, মৌজা হেমায়েতপুর, সাভার',
      description: '22.5 Decimals prime high-land situated 200m from Dhaka-Aricha Highway with 20-ft road access.',
      location: 'Hemayetpur, Savar Upazila, Dhaka District',
      purchaseValue: 1835000.0,
      currentValue: 2450000.0,
      ownershipReference: 'Deed No. 4982/2026 (Savar Sub-Registry)',
      deedNumber: 'DEED-4982/2026',
      mutationKhatian: 'RS Khatian #812, Mutation Case #1092/2026',
      landAreaDecimals: 22.5,
      status: AssetStatus.acquired,
      acquisitionDate: DateTime(2026, 4, 10),
      legalVerificationOfficer: 'Advocate Mahbubur Rahman, Supreme Court of Bangladesh',
      photos: [
        'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1524813686514-a57563d77d61?w=800&auto=format&fit=crop&q=80',
      ],
    ),
  ];

  static final List<ProfitPeriodModel> defaultProfitPeriods = [
    ProfitPeriodModel(
      id: 'pp-2026-h1',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      periodName: 'H1 2026 Interim Lease Distribution',
      periodStart: DateTime(2026, 1, 1),
      periodEnd: DateTime(2026, 6, 30),
      grossRevenue: 280000.0,
      realizedExpense: 30000.0,
      realizedProfit: 250000.0,
      distributionPool: 250000.0,
      eligibleShares: 100,
      status: ProfitPeriodStatus.closed,
      createdAt: DateTime(2026, 7, 1),
    ),
    ProfitPeriodModel(
      id: 'pp-2026-h2',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      periodName: 'H2 2026 Appreciation & Rental Yield',
      periodStart: DateTime(2026, 7, 1),
      periodEnd: DateTime(2026, 12, 31),
      grossRevenue: 320000.0,
      realizedExpense: 20000.0,
      realizedProfit: 300000.0,
      distributionPool: 300000.0,
      eligibleShares: 100,
      status: ProfitPeriodStatus.reconciling,
      createdAt: DateTime(2026, 8, 25),
    ),
  ];

  static final List<DistributionModel> defaultDistributions = [
    DistributionModel(
      id: 'dist-01',
      profitPeriodId: 'pp-2026-h1',
      periodName: 'H1 2026 Interim Lease Distribution',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      userId: 'usr-investor-01',
      investmentId: 'inv-101',
      eligibleShares: 4,
      amount: 10000.0,
      status: DistributionStatus.paid,
      paidAt: DateTime(2026, 7, 5, 11, 20),
      paymentReference: 'DIST-2026-H1-042',
      bankMfsAccount: 'bKash (01712-345678)',
    ),
    DistributionModel(
      id: 'dist-02',
      profitPeriodId: 'pp-2026-h2',
      periodName: 'H2 2026 Appreciation & Rental Yield',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      userId: 'usr-investor-01',
      investmentId: 'inv-101',
      eligibleShares: 4,
      amount: 12000.0,
      status: DistributionStatus.approved,
      bankMfsAccount: 'City Bank (A/C: 1102938475)',
    ),
  ];

  static final List<DocumentModel> defaultDocuments = [
    DocumentModel(
      id: 'doc-01',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      category: DocumentCategory.projectDeed,
      title: 'Sub-Registry Registered Title Deed (দলিল)',
      titleBn: 'সাব-রেজিস্ট্রি নিবন্ধিত মূল দলিল',
      fileName: 'LandVest100_Deed_4982_2026.pdf',
      fileSize: '4.2 MB',
      version: 'v1.0 (Certified Copy)',
      visibility: DocumentVisibility.investorOnly,
      checksumSha256: '9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e',
      uploadedAt: DateTime(2026, 4, 15),
      uploadedBy: 'Legal Compliance Cell',
    ),
    DocumentModel(
      id: 'doc-02',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      category: DocumentCategory.legal,
      title: 'Supreme Court Advocate Legal Vetting Report',
      titleBn: 'সুপ্রিম কোর্টের আইনজীবীর আইনি যাচাই প্রতিবেদন',
      fileName: 'Legal_Search_Clearance_Report_LV100.pdf',
      fileSize: '2.8 MB',
      version: 'v1.1 (Final Vetted)',
      visibility: DocumentVisibility.publicDoc,
      checksumSha256: '3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b',
      uploadedAt: DateTime(2026, 2, 8),
      uploadedBy: 'Hossain & Associates',
    ),
    DocumentModel(
      id: 'doc-03',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      category: DocumentCategory.govtApproval,
      title: 'AC Land Mutation Khatian & DCR Challan',
      titleBn: 'এসিল্যান্ড নামজারি খতিয়ান ও ডিসিআর',
      fileName: 'Mutation_Khatian_812_Savar.pdf',
      fileSize: '1.9 MB',
      version: 'v1.0',
      visibility: DocumentVisibility.investorOnly,
      checksumSha256: '8b7a6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b',
      uploadedAt: DateTime(2026, 8, 18),
      uploadedBy: 'Land Registry Dept',
    ),
    DocumentModel(
      id: 'doc-04',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      userId: 'usr-investor-01',
      category: DocumentCategory.receipt,
      title: 'Share Allocation Certificate (4 Shares)',
      titleBn: 'শেয়ার বরাদ্দ সনদপত্র (৪টি শেয়ার)',
      fileName: 'Share_Certificate_SJ_LV100_0042.pdf',
      fileSize: '1.1 MB',
      version: 'v1.0 (Official Signed)',
      visibility: DocumentVisibility.investorOnly,
      checksumSha256: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
      uploadedAt: DateTime(2026, 2, 13),
      uploadedBy: 'Swapnojatri Share Registry',
    ),
  ];

  static final List<NotificationModel> defaultNotifications = [
    NotificationModel(
      id: 'notif-01',
      title: 'H1 2026 Distribution Credited',
      titleBn: 'এইচ১ ২০২৬ লভ্যাংশ বণ্টন সম্পন্ন',
      body: '৳10,000 has been transferred to your bKash account for 4 shares in LandVest 100.',
      bodyBn: 'ল্যান্ডভেস্ট ১০০ প্রকল্পে আপনার ৪টি শেয়ারের বিপরীতে ৳১০,০০০ আপনার বিকাশ অ্যাকাউন্টে পাঠানো হয়েছে।',
      category: NotificationCategory.distribution,
      createdAt: DateTime(2026, 7, 5, 11, 25),
      isRead: false,
    ),
    NotificationModel(
      id: 'notif-02',
      title: 'AC Land Mutation Completed',
      titleBn: 'নামজারি খতিয়ান সফলভাবে চূড়ান্ত হয়েছে',
      body: 'LandVest 100 land mutation has been approved by Savar AC Land office. View documents now.',
      bodyBn: 'সাভার এসিল্যান্ড অফিস থেকে ল্যান্ডভেস্ট ১০০ জমির নামজারি চূড়ান্ত হয়েছে। দলিল ভল্টে খতিয়ান দেখুন।',
      category: NotificationCategory.project,
      createdAt: DateTime(2026, 8, 18, 16, 40),
      isRead: true,
    ),
    NotificationModel(
      id: 'notif-03',
      title: 'Share Lots Confirmed (Lots 041-044)',
      titleBn: 'শেয়ার লট বরাদ্দ নিশ্চিত হয়েছে',
      body: 'Your subscription for 4 shares (৳1,02,000) has been officially verified and allocated.',
      bodyBn: 'আপনার ৪টি শেয়ারের সাবস্ক্রিপশন (৳১,০২,০০০) যাচাইকৃত হয়ে অফিসিয়ালি বরাদ্দ হয়েছে।',
      category: NotificationCategory.investment,
      createdAt: DateTime(2026, 2, 13, 10, 20),
      isRead: true,
    ),
  ];

  static final KycModel defaultKyc = KycModel(
    id: 'kyc-usr-01',
    userId: 'usr-investor-01',
    fullName: 'Ohiur Rahman Ohi',
    fatherName: 'Motiur Rahman',
    motherName: 'Salma Khatun',
    nidNumber: '19922692019000452',
    dateOfBirth: '14 May 1992',
    presentAddress: 'House 42, Road 11, Banani, Dhaka-1213',
    permanentAddress: 'Village: Uttarpara, P.O: Savar, Dhaka',
    bankName: 'City Bank PLC',
    bankAccountNumber: '1102938475001',
    routingNumber: '225261890',
    nidFrontUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    nidBackUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    status: KycStatus.verified,
    submittedAt: DateTime(2026, 2, 10),
    verifiedAt: DateTime(2026, 2, 11),
    verifiedBy: 'Compliance Cell (Tanvir Ahmed)',
    nominee: NomineeModel(
      name: 'Nusrat Jahan',
      relationship: 'Spouse (স্ত্রী)',
      phone: '+880 1823-456789',
      nidNumber: '19952692019000889',
      percentage: 100.0,
    ),
  );

  static final List<AuditLogModel> defaultAuditLogs = [
    AuditLogModel(
      id: 'aud-901',
      actorName: 'Tanvir Ahmed',
      actorRole: 'Finance Manager',
      action: 'APPROVE_PAYMENT',
      entityType: 'Payment',
      entityId: 'TXN-CBL-8920194',
      details: 'Verified ৳102,000 via City Bank statement for investor Ohiur Rahman (inv-101)',
      ipAddress: '103.145.118.22',
      timestamp: DateTime(2026, 2, 13, 10, 15),
    ),
    AuditLogModel(
      id: 'aud-902',
      actorName: 'Tanvir Ahmed',
      actorRole: 'Super Admin',
      action: 'ALLOCATE_SHARE_LOTS',
      entityType: 'ShareAllocation',
      entityId: 'proj-lv-100',
      details: 'Allocated lots LOT-041 to LOT-044 in LandVest 100 (Total allocated: 74/100)',
      ipAddress: '103.145.118.22',
      timestamp: DateTime(2026, 2, 13, 10, 16),
    ),
    AuditLogModel(
      id: 'aud-903',
      actorName: 'Tanvir Ahmed',
      actorRole: 'Finance Manager',
      action: 'APPROVE_EXPENSE',
      entityType: 'Expense',
      entityId: 'exp-05',
      details: 'Approved mutation fee ৳25,000 payable to AC Land Office Savar',
      ipAddress: '103.145.118.22',
      timestamp: DateTime(2026, 8, 16, 14, 05),
    ),
  ];
}
