import 'package:swapnojatri/core/localization/app_strings.dart';
import 'package:swapnojatri/data/models/project_model.dart';
import 'package:swapnojatri/data/models/investment_model.dart';
import 'package:swapnojatri/data/models/transaction_model.dart';
import 'package:swapnojatri/data/models/expense_model.dart';
import 'package:swapnojatri/data/models/asset_model.dart';
import 'package:swapnojatri/data/models/profit_period_model.dart';
import 'package:swapnojatri/data/models/distribution_model.dart';
import 'package:swapnojatri/data/models/document_model.dart';
import 'package:swapnojatri/data/models/notification_model.dart';
import 'package:swapnojatri/data/models/kyc_model.dart';
import 'package:swapnojatri/data/models/audit_log_model.dart';
import 'package:swapnojatri/data/models/user_model.dart';

/// Seed data representing real-world Swapnojatri operations and LandVest 100
class ProjectSeeds {
  ProjectSeeds._();

  static final ProjectModel landVest100 = ProjectModel(
    id: 'proj-lv-100',
    code: 'LV100',
    name: 'LandVest 100',
    nameBn: 'ল্যান্ডভেস্ট ১০০',
    category: 'Real Estate & Land Project',
    projectCategory: ProjectCategory.realEstate,
    categoryNameBn: 'রিয়েল এস্টেট / জমি',
    location: 'Washpur Tower Road (Past Bosila Bridge), Dhaka',
    description: AppStrings.landVestDescEn,
    descriptionBn: AppStrings.landVestDescBn,
    targetFund: 2550000.0,
    totalShares: 100,
    pricePerShare: 25500.0,
    minShares: 1,
    maxShares: 4,
    allocatedShares: 74,
    status: ProjectStatus.active,
    startDate: DateTime(2026, 1, 15),
    targetEndDate: DateTime(2027, 6, 30),
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&auto=format&fit=crop&q=80',
    philosophyQuoteBn: AppStrings.philosophyQuoteBn,
    philosophyQuoteEn: AppStrings.philosophyQuoteEn,
    profitModelBn: 'প্রকল্পভিত্তিক লাভ বণ্টন (Profit-Sharing Model) — কোনো ব্যক্তি মালিকানার আইনি জটিলতা বা খতিয়ান তদারকি ছাড়া নিট মুনাফার সমানুপাতিক বণ্টন।',
    profitModelEn: 'Transparent project profit distribution based on subscribed shares, without personal deed management hassles.',
    highlights: [
      '১০০টি সুনির্দিষ্ট শেয়ারে মোট ২৫,৫০,০০০ টাকার সুরক্ষিত প্রকল্প তহবিল',
      'প্রতি শেয়ার ২৫,৫০০ টাকায় সামর্থ্য অনুযায়ী ১, ২, ৩ বা ৪+ শেয়ার নেওয়ার সুযোগ',
      'বসিলা সংলগ্ন ওয়াশপুর টাওয়ার রোডে সফল টিম দ্বারা পরিচালিত',
      'প্রকল্প সমাপ্তি ও নগদায়নে সমহারে সম্পূর্ণ নিট মুনাফা বণ্টন',
    ],
    trackRecords: const [
      TrackRecordProject(
        nameBn: 'স্বপ্ননীড় প্যালেস',
        nameEn: 'Swapnonir Palace',
        detailsBn: '১১ কাঠা জমিতে ১১ তলা আধুনিক রেসিডেন্সিয়াল ভবন',
        detailsEn: '11 Katha plot, 11-storey residential building',
        statusBn: 'এখন বসবাস সম্পন্ন',
        statusEn: 'Completed & Handed Over',
      ),
      TrackRecordProject(
        nameBn: 'স্বপ্নডানা',
        nameEn: 'Swapnodana',
        detailsBn: '১১.২৭ কাঠা জমিতে ১৩ তলা আধুনিক প্রকল্প',
        detailsEn: '11.27 Katha plot, 13-storey modern structure',
        statusBn: '৯ম তলার ছাদ ঢালাই কাজ চলমান',
        statusEn: '9th Floor Slab Ongoing',
      ),
      TrackRecordProject(
        nameBn: 'জল ও জ্যোৎস্না',
        nameEn: 'Jol O Jyotsna',
        detailsBn: '১৪ কাঠা জমিতে ১৪ তলা নান্দনিক টাওয়ার',
        detailsEn: '14 Katha plot, 14-storey landmark tower',
        statusBn: 'পাইলিং ও ফাউন্ডেশনের কাজ চলমান',
        statusEn: 'Piling & Foundation Ongoing',
      ),
      TrackRecordProject(
        nameBn: 'গ্রীণ টাওয়ার',
        nameEn: 'Green Tower',
        detailsBn: '৩০ কাঠা সুবিশাল জমিতে ১৬ তলা মেগা প্রজেক্ট',
        detailsEn: '30 Katha mega plot, 16-storey residential community',
        statusBn: 'শেয়ার বরাদ্দ ও বিক্রয় চলছে',
        statusEn: 'Share Allocation Active',
      ),
    ],
    milestones: [
      Milestone(
        id: 'm1',
        title: 'Project Initiation & Land Selection',
        titleBn: 'প্রকল্প শুরু ও জমি চূড়ান্তকরণ',
        description: 'Site selection at Washpur Tower Road with market viability audit.',
        date: DateTime(2026, 1, 15),
        isCompleted: true,
      ),
      Milestone(
        id: 'm2',
        title: 'LandVest 100 Funding Launch (100 Shares)',
        titleBn: 'তহবিল সংগ্রহ শুরু (১০০ শেয়ার)',
        description: 'Official opening of LandVest 100 subscription at ৳25,500/share.',
        date: DateTime(2026, 2, 1),
        isCompleted: true,
      ),
      Milestone(
        id: 'm3',
        title: 'Land Acquisition & Site Fencing',
        titleBn: 'জমি সংরক্ষণ ও সীমানা নির্ধারণ',
        description: 'Execution of agreement, site securing and boundary protection.',
        date: DateTime(2026, 4, 10),
        isCompleted: true,
      ),
      Milestone(
        id: 'm4',
        title: 'Interim Lease & Value Addition',
        titleBn: 'মূল্য সংযোজন ও উন্নয়ন প্রস্তুতি',
        description: 'Site development and commercial viability enhancement.',
        date: DateTime(2026, 6, 20),
        isCompleted: true,
      ),
      Milestone(
        id: 'm5',
        title: 'Strategic Monetization / Exit Phase',
        titleBn: 'সম্পদ নগদায়ন ও নিট লাভ বণ্টন',
        description: 'Asset appreciation monetization and 100% net profit distribution to all 100 shares.',
        date: DateTime(2027, 6, 30),
        isCompleted: false,
      ),
    ],
  );

  static final ProjectModel agroVest1 = ProjectModel(
    id: 'proj-agro-01',
    code: 'AGRO01',
    name: 'Swapnojatri Agro-Farm (Season 1)',
    nameBn: 'স্বপ্নযাত্রী স্মার্ট এগ্রো (সিজন ১)',
    category: 'Agricultural & Organic Farming',
    projectCategory: ProjectCategory.agroFarming,
    categoryNameBn: 'কৃষি ও ফার্মিং',
    location: 'Singair, Manikganj (High Yield Agro Zone)',
    description: 'High-density seasonal agro farming, high-yield vegetable crops & dairy production with transparent quarterly profit distribution.',
    descriptionBn: 'উন্নত প্রযুক্তিনির্ভর সমন্বিত কৃষি ও ফার্মিং প্রকল্প। স্বল্পমেয়াদী ফসল ও ডেইরি উৎপাদন থেকে ত্রৈমাসিক লভ্যাংশ বণ্টন।',
    targetFund: 3000000.0,
    totalShares: 200,
    pricePerShare: 15000.0,
    minShares: 1,
    maxShares: 10,
    allocatedShares: 45,
    status: ProjectStatus.active,
    startDate: DateTime(2026, 6, 1),
    targetEndDate: DateTime(2027, 5, 31),
    imageUrl: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?w=800&auto=format&fit=crop&q=80',
    philosophyQuoteBn: '“টেকসই কৃষিতে আধুনিক প্রযুক্তির সঠিক বিনিয়োগই নিশ্চিত করে স্বচ্ছ ও সর্বোচ্চ মুনাফা।”',
    philosophyQuoteEn: '"Modern technology in sustainable agriculture ensures optimal productivity and transparent dividends."',
    profitModelBn: 'ফসল উত্তোলন ও বিক্রয় পরবর্তী ত্রৈমাসিক ভিত্তিতে নিট লভ্যাংশ সরাসরি ব্যাংক/বিকাশ একাউন্টে জমা।',
    profitModelEn: 'Quarterly dividend payouts directly to verified Bank/bKash accounts following harvest sales.',
    highlights: [
      'সমন্বিত অর্গানিক শাকসবজি, ডাল ও ডেইরি ফার্মিং উদ্যোগ',
      'প্রতি শেয়ার ১৫,০০০ টাকা (মোট ২০০ শেয়ার)',
      'কৃষিবিদ ও বিশেষজ্ঞদের সার্বক্ষণিক প্রত্যক্ষ তত্ত্বাবধান',
      'ত্রৈমাসিক লভ্যাংশ প্রাপ্তির সুবর্ণ সুযোগ',
    ],
    trackRecords: const [],
    milestones: [
      Milestone(
        id: 'ag-m1',
        title: 'Land Lease & Soil Preparation',
        titleBn: 'জমি লিজ ও মাটি প্রস্তুতি',
        description: 'Secured fertile land in Singair and organic soil treatment.',
        date: DateTime(2026, 6, 1),
        isCompleted: true,
      ),
      Milestone(
        id: 'ag-m2',
        title: 'High-Yield Seeding & Irrigation Setup',
        titleBn: 'উন্নত বীজ বপন ও সেচ ব্যবস্থা',
        description: 'Smart drip irrigation installation and initial seeding.',
        date: DateTime(2026, 7, 15),
        isCompleted: true,
      ),
      Milestone(
        id: 'ag-m3',
        title: 'First Cycle Harvest & Market Distribution',
        titleBn: '১ম ধাপের ফসল উত্তোলন ও বাজারজাতকরণ',
        description: 'Wholesale market supply and initial quarterly dividend calculation.',
        date: DateTime(2026, 10, 30),
        isCompleted: false,
      ),
    ],
  );

  static final ProjectModel landVest90 = ProjectModel(
    id: 'proj-lv-90',
    code: 'LV90',
    name: 'LandVest 90 (Purbachal Sector 22)',
    nameBn: 'ল্যান্ডভেস্ট ৯০ (পূর্বাচল সেক্টর ২২)',
    category: 'Commercial Highway Land',
    projectCategory: ProjectCategory.realEstate,
    categoryNameBn: 'রিয়েল এস্টেট / জমি',
    location: 'Sector 22, Purbachal, Dhaka',
    description: 'Prime commercial land in Purbachal New Town Project with verified development potential.',
    descriptionBn: 'পূর্বাচল নতুন শহর সেক্টর ২২ এ বাণিজ্যিক জমি প্রকল্প, সফলভাবে শতভাগ সাবস্ক্রিপশন সম্পন্ন।',
    targetFund: 2200000.0,
    totalShares: 100,
    pricePerShare: 22000.0,
    minShares: 1,
    maxShares: 4,
    allocatedShares: 100,
    status: ProjectStatus.funded,
    startDate: DateTime(2025, 6, 1),
    targetEndDate: DateTime(2026, 12, 31),
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&auto=format&fit=crop&q=80',
    highlights: [
      'রাজউক পূর্বাচল ৩০০ ফুট এক্সপ্রেসওয়ের সন্নিকটে',
      'সকল ১০০টি শেয়ার ১০০% সাবস্ক্রাইব সম্পন্ন',
      'পরিকল্পিত মুনাফা বণ্টন চলমান',
    ],
    milestones: [],
  );

  static final UserModel defaultInvestor = UserModel(
    id: 'usr-investor-01',
    name: 'Mashkurul Alam Ohi',
    phone: '+880 1712-345678',
    email: 'mashkurul.ohi@swapnojatri.com',
    role: UserRole.investor,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    isKycVerified: true,
    memberSince: DateTime(2026, 2, 10),
  );

  static final UserModel defaultAdmin = UserModel(
    id: 'usr-admin-01',
    name: 'Tanvir Ahmed',
    phone: '+880 1819-998877',
    email: 'tanvir.admin@swapnojatri.com',
    role: UserRole.admin,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    isKycVerified: true,
    memberSince: DateTime(2025, 11, 1),
  );

  static final List<InvestmentModel> defaultInvestments = [
    InvestmentModel(
      id: 'inv-101',
      investmentNo: 'SJ-LV100-0042',
      userId: 'usr-investor-01',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      shares: 4,
      unitPrice: 25500.0,
      grossAmount: 102000.0,
      fees: 0.0,
      netAmount: 102000.0,
      status: InvestmentStatus.allocated,
      allocatedLotNumbers: ['LOT-041', 'LOT-042', 'LOT-043', 'LOT-044'],
      paymentMethod: 'Bank Transfer (City Bank)',
      paymentReference: 'TXN-CBL-8920194',
      createdAt: DateTime(2026, 2, 12, 14, 30),
      verifiedAt: DateTime(2026, 2, 13, 10, 15),
    ),
  ];

  static final List<TransactionModel> defaultTransactions = [
    TransactionModel(
      id: 'txn-501',
      investmentId: 'inv-101',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      projectNameBn: 'ল্যান্ডভেস্ট ১০০',
      userId: 'usr-investor-01',
      type: TransactionType.investment,
      direction: TransactionDirection.debit,
      amount: 102000.0,
      balanceAfter: 102000.0,
      reference: 'TXN-CBL-8920194',
      paymentMethod: 'City Bank Ltd (EFTN)',
      status: TransactionStatus.completed,
      createdAt: DateTime(2026, 2, 12, 14, 30),
      description: 'Subscription for 4 Shares in LandVest 100 (Lots 041-044)',
      descriptionBn: 'ল্যান্ডভেস্ট ১০০ প্রকল্পে ৪টি শেয়ার সাবস্ক্রিপশন (লট ০৪১-০৪৪)',
    ),
    TransactionModel(
      id: 'txn-502',
      investmentId: 'inv-101',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      projectNameBn: 'ল্যান্ডভেস্ট ১০০',
      userId: 'usr-investor-01',
      type: TransactionType.profitDistribution,
      direction: TransactionDirection.credit,
      amount: 10000.0,
      balanceAfter: 112000.0,
      reference: 'DIST-2026-H1-042',
      paymentMethod: 'bKash Merchant Payout',
      status: TransactionStatus.completed,
      createdAt: DateTime(2026, 7, 5, 11, 20),
      description: 'H1 2026 Interim Profit Distribution (4 Shares @ ৳2,500)',
      descriptionBn: 'এইচ১ ২০২৬ অন্তর্বর্তীকালীন লভ্যাংশ বিতরণ (৪টি শেয়ার @ ৳২,৫০০)',
    ),
    TransactionModel(
      id: 'txn-503',
      investmentId: 'inv-101',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      projectNameBn: 'ল্যান্ডভেস্ট ১০০',
      userId: 'usr-investor-01',
      type: TransactionType.investment,
      direction: TransactionDirection.debit,
      amount: 25500.0,
      balanceAfter: 137500.0,
      reference: 'TXN-CBL-9912034',
      paymentMethod: 'City Bank Ltd (EFTN)',
      status: TransactionStatus.pending,
      createdAt: DateTime(2026, 8, 28, 16, 45),
      description: 'Pending Subscription for 1 Share in LandVest 100',
      descriptionBn: 'ল্যান্ডভেস্ট ১০০ প্রকল্পে ১টি শেয়ার সাবস্ক্রিপশন (যাচাইাধীন)',
    ),
  ];

  static final List<ExpenseModel> defaultExpenses = [
    ExpenseModel(
      id: 'exp-01',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      category: 'Project Asset Acquisition',
      description: 'Land acquisition and vendor settlement for project site',
      payee: 'Haji Mohammad Ali',
      amount: 1550000.0,
      expenseDate: DateTime(2026, 4, 10),
      status: ExpenseStatus.approved,
      approvedBy: 'Tanvir Ahmed (Finance Manager)',
      documentRef: 'VOUCHER-EXP-001.pdf',
      voucherNo: 'VCH-LV100-01',
    ),
    ExpenseModel(
      id: 'exp-02',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      category: 'Legal & Agreement Execution',
      description: 'Legal vetting, stamp duties and partnership documentation',
      payee: 'Hossain & Associates Legal Firm',
      amount: 285000.0,
      expenseDate: DateTime(2026, 4, 12),
      status: ExpenseStatus.approved,
      approvedBy: 'Tanvir Ahmed (Finance Manager)',
      documentRef: 'TAX-CHALLAN-891.pdf',
      voucherNo: 'VCH-LV100-02',
    ),
    ExpenseModel(
      id: 'exp-03',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      category: 'Site Demarcation & Fencing',
      description: 'Perimeter fencing, security boundary & survey charges',
      payee: 'Dhaka Civil Engineering Works',
      amount: 125000.0,
      expenseDate: DateTime(2026, 6, 22),
      status: ExpenseStatus.approved,
      approvedBy: 'Tanvir Ahmed (Finance Manager)',
      documentRef: 'FENCE-BILL-33.pdf',
      voucherNo: 'VCH-LV100-03',
    ),
  ];

  static final List<AssetModel> defaultAssets = [
    AssetModel(
      id: 'ast-lv-01',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      assetType: 'Project Land Asset (প্রকল্প জমি)',
      title: 'Washpur Tower Road Project Site',
      titleBn: 'ওয়াশপুর টাওয়ার রোড প্রকল্প স্থান',
      description: 'Prime project site situated near Washpur Tower Road with excellent growth corridor.',
      location: 'Washpur, Tower Road, Bosila, Dhaka',
      purchaseValue: 1835000.0,
      currentValue: 2450000.0,
      ownershipReference: 'Project Asset Vault #LV100',
      deedNumber: 'PRJ-LV100-ASSET',
      mutationKhatian: 'Verified Project Asset',
      landAreaDecimals: 22.5,
      status: AssetStatus.acquired,
      acquisitionDate: DateTime(2026, 4, 10),
      legalVerificationOfficer: 'Advocate Mahbubur Rahman, Supreme Court of Bangladesh',
      photos: [
        'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1524813686514-a57563d77d61?w=800&auto=format&fit=crop&q=80',
      ],
    ),
  ];

  static final List<ProfitPeriodModel> defaultProfitPeriods = [
    ProfitPeriodModel(
      id: 'pp-2026-h1',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      periodName: 'H1 2026 Interim Profit Distribution',
      periodStart: DateTime(2026, 1, 1),
      periodEnd: DateTime(2026, 6, 30),
      grossRevenue: 280000.0,
      realizedExpense: 30000.0,
      realizedProfit: 250000.0,
      distributionPool: 250000.0,
      eligibleShares: 100,
      status: ProfitPeriodStatus.closed,
      createdAt: DateTime(2026, 7, 1),
    ),
    ProfitPeriodModel(
      id: 'pp-2026-h2',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      periodName: 'H2 2026 Appreciation & Project Yield',
      periodStart: DateTime(2026, 7, 1),
      periodEnd: DateTime(2026, 12, 31),
      grossRevenue: 320000.0,
      realizedExpense: 20000.0,
      realizedProfit: 300000.0,
      distributionPool: 300000.0,
      eligibleShares: 100,
      status: ProfitPeriodStatus.reconciling,
      createdAt: DateTime(2026, 8, 25),
    ),
  ];

  static final List<DistributionModel> defaultDistributions = [
    DistributionModel(
      id: 'dist-01',
      profitPeriodId: 'pp-2026-h1',
      periodName: 'H1 2026 Interim Profit Distribution',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      userId: 'usr-investor-01',
      investmentId: 'inv-101',
      eligibleShares: 4,
      amount: 10000.0,
      status: DistributionStatus.paid,
      paidAt: DateTime(2026, 7, 5, 11, 20),
      paymentReference: 'DIST-2026-H1-042',
      bankMfsAccount: 'bKash (01712-345678)',
    ),
    DistributionModel(
      id: 'dist-02',
      profitPeriodId: 'pp-2026-h2',
      periodName: 'H2 2026 Appreciation & Project Yield',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      userId: 'usr-investor-01',
      investmentId: 'inv-101',
      eligibleShares: 4,
      amount: 12000.0,
      status: DistributionStatus.approved,
      bankMfsAccount: 'City Bank (A/C: 1102938475)',
    ),
  ];

  static final List<DocumentModel> defaultDocuments = [
    DocumentModel(
      id: 'doc-01',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      category: DocumentCategory.projectDeed,
      title: 'Project Partnership & Profit Sharing Agreement',
      titleBn: 'প্রকল্প অংশীদারিত্ব ও লভ্যাংশ বণ্টন চুক্তি',
      fileName: 'LandVest100_Partnership_Agreement.pdf',
      fileSize: '3.4 MB',
      version: 'v1.0 (Official Agreement)',
      visibility: DocumentVisibility.investorOnly,
      checksumSha256: '9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e',
      uploadedAt: DateTime(2026, 4, 15),
      uploadedBy: 'Swapnojatri Compliance Cell',
    ),
    DocumentModel(
      id: 'doc-02',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      category: DocumentCategory.legal,
      title: 'Legal Vetting & Compliance Clearance Report',
      titleBn: 'আইনি যাচাই ও কমপ্লায়েন্স অনুমোদন প্রতিবেদন',
      fileName: 'Legal_Search_Clearance_Report_LV100.pdf',
      fileSize: '2.8 MB',
      version: 'v1.1 (Final Vetted)',
      visibility: DocumentVisibility.publicDoc,
      checksumSha256: '3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b',
      uploadedAt: DateTime(2026, 2, 8),
      uploadedBy: 'Hossain & Associates',
    ),
    DocumentModel(
      id: 'doc-03',
      projectId: 'proj-lv-100',
      projectName: 'LandVest 100',
      userId: 'usr-investor-01',
      category: DocumentCategory.receipt,
      title: 'LandVest 100 Share Certificate (4 Shares)',
      titleBn: 'ল্যান্ডভেস্ট ১০০ শেয়ার সনদপত্র (৪টি শেয়ার)',
      fileName: 'Share_Certificate_SJ_LV100_0042.pdf',
      fileSize: '1.1 MB',
      version: 'v1.0 (Official Signed)',
      visibility: DocumentVisibility.investorOnly,
      checksumSha256: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
      uploadedAt: DateTime(2026, 2, 13),
      uploadedBy: 'Swapnojatri Share Registry',
    ),
  ];

  static final List<NotificationModel> defaultNotifications = [
    NotificationModel(
      id: 'notif-01',
      title: 'H1 2026 Distribution Credited',
      titleBn: 'এইচ১ ২০২৬ লভ্যাংশ বণ্টন সম্পন্ন',
      body: '৳10,000 has been transferred to your bKash account for 4 shares in LandVest 100.',
      bodyBn: 'ল্যান্ডভেস্ট ১০০ প্রকল্পে আপনার ৪টি শেয়ারের বিপরীতে ৳১০,০০০ আপনার বিকাশ অ্যাকাউন্টে জমা হয়েছে।',
      category: NotificationCategory.distribution,
      createdAt: DateTime(2026, 7, 5, 11, 25),
      isRead: false,
    ),
    NotificationModel(
      id: 'notif-02',
      title: 'AgroVest Farming Opportunity Announced',
      titleBn: 'নতুন প্রকল্প: স্বপ্নযাত্রী স্মার্ট এগ্রো উন্মোচিত',
      body: 'Explore modern agricultural profit-sharing with quarterly dividends at ৳15,000/share.',
      bodyBn: 'ত্রৈমাসিক লভ্যাংশসহ স্মার্ট এগ্রো ফার্মিং প্রকল্পে প্রতি শেয়ার ১৫,০০০ টাকায় অংশ নিন।',
      category: NotificationCategory.project,
      createdAt: DateTime(2026, 8, 20, 10, 00),
      isRead: true,
    ),
    NotificationModel(
      id: 'notif-03',
      title: 'LandVest 100 Shares Confirmed',
      titleBn: 'ল্যান্ডভেস্ট ১০০ শেয়ার বরাদ্দ নিশ্চিত হয়েছে',
      body: 'Your subscription for 4 shares (৳1,02,000) has been officially verified.',
      bodyBn: 'আপনার ৪টি শেয়ারের সাবস্ক্রিপশন (৳১,০২,০০০) যাচাইকৃত হয়ে অফিসিয়ালি বরাদ্দ হয়েছে।',
      category: NotificationCategory.investment,
      createdAt: DateTime(2026, 2, 13, 10, 20),
      isRead: true,
    ),
  ];

  static final KycModel defaultKyc = KycModel(
    id: 'kyc-usr-01',
    userId: 'usr-investor-01',
    fullName: 'Mashkurul Alam Ohi',
    fatherName: 'Motiur Rahman',
    motherName: 'Salma Khatun',
    nidNumber: '19922692019000452',
    dateOfBirth: '14 May 1992',
    presentAddress: 'House 42, Road 11, Banani, Dhaka-1213',
    permanentAddress: 'Village: Uttarpara, P.O: Savar, Dhaka',
    bankName: 'City Bank PLC',
    bankAccountNumber: '1102938475001',
    routingNumber: '225261890',
    nidFrontUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    nidBackUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    status: KycStatus.verified,
    submittedAt: DateTime(2026, 2, 10),
    verifiedAt: DateTime(2026, 2, 11),
    verifiedBy: 'Compliance Cell (Tanvir Ahmed)',
    nominee: NomineeModel(
      name: 'Nusrat Jahan',
      relationship: 'Spouse (স্ত্রী)',
      phone: '+880 1823-456789',
      nidNumber: '19952692019000889',
      percentage: 100.0,
    ),
  );

  static final List<AuditLogModel> defaultAuditLogs = [
    AuditLogModel(
      id: 'aud-901',
      actorName: 'Tanvir Ahmed',
      actorRole: 'Finance Manager',
      action: 'APPROVE_PAYMENT',
      actionBn: 'পেমেন্ট অনুমোদন',
      entityType: 'Payment',
      entityId: 'TXN-CBL-8920194',
      details: 'Verified ৳102,000 via City Bank statement for investor Mashkurul Alam Ohi (inv-101)',
      detailsBn: 'সিটি ব্যাংক বিবরণী অনুযায়ী বিনিয়োগকারী মাশকুরুল আলম ওহির ৳১,০২,০০০ পেমেন্ট যাচাইকৃত',
      ipAddress: '103.145.118.22',
      timestamp: DateTime(2026, 2, 13, 10, 15),
    ),
    AuditLogModel(
      id: 'aud-902',
      actorName: 'Tanvir Ahmed',
      actorRole: 'Super Admin',
      action: 'ALLOCATE_SHARE_LOTS',
      actionBn: 'শেয়ার লট বরাদ্দ',
      entityType: 'ShareAllocation',
      entityId: 'proj-lv-100',
      details: 'Allocated 4 shares in LandVest 100 (Total allocated: 74/100)',
      detailsBn: 'ল্যান্ডভেস্ট ১০০ প্রকল্পে ৪টি শেয়ার বরাদ্দ সম্পন্ন (মোট বরাদ্দ: ৭৪/১০০)',
      ipAddress: '103.145.118.22',
      timestamp: DateTime(2026, 2, 13, 10, 16),
    ),
  ];
}
